import { useTranslation } from 'react-i18next';

export default function Terms() {
  const { t } = useTranslation();
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-gray max-w-none space-y-6">
        <p className="text-sm text-gray-500">Last updated: March 9, 2026</p>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using PetPawSphere ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">2. Description of Service</h2>
          <p>PetPawSphere is an AI-powered pet breeding compatibility platform operating in the United Arab Emirates. The Platform provides pet profile management, AI-powered breeding compatibility analysis, veterinary document scanning, and pet health diagnostics.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">3. User Accounts</h2>
          <p>You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials. You must be at least 18 years old to use the Platform.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">4. AI Disclaimers</h2>
          <p>The Platform uses artificial intelligence for pet compatibility analysis, breed detection, and health assessments. These are preliminary assessments only and do NOT constitute veterinary medical advice. Always consult a licensed UAE veterinarian before making breeding or health decisions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">5. User Conduct</h2>
          <p>You agree not to: upload fraudulent pet profiles, misrepresent pet health records, use the Platform for illegal breeding practices, or violate UAE animal welfare laws (Federal Law No. 16 of 2007).</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">6. Breeding Contracts</h2>
          <p>Breeding contracts generated by the Platform are AI-assisted drafts. Both parties must review and agree to contract terms. PetPawSphere is not a party to any breeding agreement and bears no liability for disputes between users.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">7. Intellectual Property</h2>
          <p>The Platform and its AI models are owned by TAURUS AI Corp. Users retain ownership of their content (photos, descriptions) but grant PetPawSphere a non-exclusive license to display and process this content.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">8. Limitation of Liability</h2>
          <p>PetPawSphere shall not be liable for any damages arising from AI assessments, breeding outcomes, or user-to-user interactions. The Platform is provided "as is" without warranties.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">9. Governing Law</h2>
          <p>These Terms are governed by the laws of the United Arab Emirates. Any disputes shall be resolved in the courts of Dubai, UAE.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-3">10. Contact</h2>
          <p>For questions about these Terms, contact us at legal@petpawsphere.com</p>
        </section>
      </div>
    </div>
  );
}
